### ISSUE TITLE
Faktory server crash

### ISSUE THREAD

**Issue by International** [contribsys/faktory#133]
Hi everyone,

I'd like to talk about 2 things in this issue.

1. Is there an API that would allow me to list previously executed jobs?
2. While looking through the ruby code, and testing out some code in the console ( trying more or less to accomplish point no.1 ), I ran into the following problem:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x41fb964]

goroutine 2273 [running]:
github.com/contribsys/faktory/manager.(*manager).Fetch(0xc42007da10, 0x4532a00, 0xc420188120, 0x0, 0x0, 0xc42045a080, 0x0, 0x0, 0x970000c4204b4016, 0x6, ...)
	/private/tmp/faktory-20180109-60885-ysmqcq/faktory-0.7.0-1/src/github.com/contribsys/faktory/manager/manager.go:196 +0x2d4
github.com/contribsys/faktory/server.fetch(0xc420390060, 0xc420120000, 0xc4204b4016, 0x5)
	/private/tmp/faktory-20180109-60885-ysmqcq/faktory-0.7.0-1/src/github.com/contribsys/faktory/server/commands.go:81 +0x14c
github.com/contribsys/faktory/server.(*Server).processLines(0xc420120000, 0xc420390060)
	/private/tmp/faktory-20180109-60885-ysmqcq/faktory-0.7.0-1/src/github.com/contribsys/faktory/server/server.go:299 +0x232
github.com/contribsys/faktory/server.(*Server).Run.func1(0xc420120000, 0x4534620, 0xc42000e0d0)
	/private/tmp/faktory-20180109-60885-ysmqcq/faktory-0.7.0-1/src/github.com/contribsys/faktory/server/server.go:147 +0x5c
created by github.com/contribsys/faktory/server.(*Server).Run
	/private/tmp/faktory-20180109-60885-ysmqcq/faktory-0.7.0-1/src/github.com/contribsys/faktory/server/server.go:142 +0x247
```

I'm running faktory 0.7.0, by itself in a terminal:
```
$ faktory
```

and in another terminal, I did this:
```
> irb
2.3.0 :001 > require "faktory_worker_ruby"
 => true
2.3.0 :002 > Faktory.server{|conn| conn.fetch}
```

I know that a normal user would probably not even call this API directly, or if they do, they'll probably pass a queue name. I've looked a bit through the go code, and the `Fetch` method will have queues passed an empty array, in which case, this line:
```
var first storage.Queue
```

will end up being nil when called here:
```
// scanned through our queues, no jobs were available
// we should block for a moment, awaiting a job to be
// pushed.  this allows us to pick up new jobs in µs
// rather than seconds.
data, err := first.BPop(ctx)
```

My guess is that before the BPop is attempted, there could be something like this:
```

	if first == nil {
		return nil, fmt.Errorf("queue name must be specified")
	}

```

which, would keep the server from crashing, and it would return a proper error to the client:
```
2.3.0 :011 > Faktory.server{|conn| conn.fetch}
Faktory::CommandError: ERR queue name must be specified
```

**Comment by mperham** [comment]
1. there is not.  if you want to retain results, you'd need to persist that in your app somehow.
2. good catch.  fatch must be called with one or more queue names.  We need to validate this.
