### ISSUE TITLE
Index page slow under load

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#156]
Lots of identical backtraces like this.  Looks like trawling through History is slow under load.  Possible RocksDB merge issue?  Investigate.

```
goroutine 2213 [syscall, 3 minutes]:
runtime.cgocall(0x42c1dd0, 0xc4203ad428, 0x29)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/cgocall.go:128 +0x64 fp=0xc4203ad3e8 sp=0xc4203ad3b0 pc=0x4005274
github.com/contribsys/faktory/vendor/github.com/contribsys/gorocksdb._Cfunc_rocksdb_get_cf(0x6406db0, 0x6442b50, 0x6406da0, 0xc420336260, 0x14, 0xc4203e4250, 0xc42056a078, 0x0)
	_cgo_gotypes.go:1285 +0x4e fp=0xc4203ad428 sp=0xc4203ad3e8 pc=0x41c8f9e
github.com/contribsys/faktory/vendor/github.com/contribsys/gorocksdb.(*DB).GetBytesCF.func1(0x6406db0, 0x6442b50, 0x6406da0, 0xc420336260, 0x14, 0xc4203e4250, 0xc42056a078, 0xc420336240)
	/Users/mikeperham/src/github.com/contribsys/faktory/vendor/github.com/contribsys/gorocksdb/db.go:273 +0x169 fp=0xc4203ad478 sp=0xc4203ad428 pc=0x41d2319
github.com/contribsys/faktory/vendor/github.com/contribsys/gorocksdb.(*DB).GetBytesCF(0xc4200f3440, 0xc42056a070, 0xc42000e0a8, 0xc420336260, 0x14, 0x20, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mikeperham/src/github.com/contribsys/faktory/vendor/github.com/contribsys/gorocksdb/db.go:273 +0xd7 fp=0xc4203ad4f0 sp=0xc4203ad478 pc=0x41cd9d7
github.com/contribsys/faktory/storage.(*rocksStore).History(0xc42017e000, 0x1e, 0xc420470370, 0x0, 0x0)
	/Users/mikeperham/src/github.com/contribsys/faktory/storage/history.go:56 +0x271 fp=0xc4203ad5f0 sp=0xc4203ad4f0 pc=0x41f1791
github.com/contribsys/faktory/webui.processedHistory(0xc42035ec00, 0xc4202d0000, 0x4383739)
	/Users/mikeperham/src/github.com/contribsys/faktory/webui/helpers.go:301 +0xbd fp=0xc4203ad658 sp=0xc4203ad5f0 pc=0x42960ad
github.com/contribsys/faktory/webui.ego_index.func1()
```

**Comment by mperham** [comment]
The History call makes 90*2 calls to GetCF to get the stats for each day.  We can cache 89 out of 90 of those calls.

**Comment by mperham** [comment]
The issue appears to be the presence of lots of Merge records associated with a key we are Get'ting.

For each job we process, we fire off an increment of the "Processed:2018-06-28" key, which is a uint64 counter that uses the Merge operator.  The issue is that when we are processing 1000+ jobs/sec, the Merge records for that key pile up and we can't call Get() without RocksDB calling our merge function many, many thousands of times, which takes a few seconds.

I have no idea how to tell RocksDB to compact the merge records frequently, in practice it is not compacting them.  I'll need to add an in-memory cache so we avoid calling Get() on a key which is changing rapidly.

**Comment by mperham** [comment]
Related: https://github.com/facebook/rocksdb/issues/1988
