### ISSUE TITLE
worker thread got OSError: [WinError 6] The handle is invalid when stop worker from Web UI

### ISSUE THREAD

**Issue by ChrisXiaoShu** [contribsys/faktory#264]
- issue describe 
I run the faktory server by runing docker image and follow [Getting Started Python](https://www.mikeperham.com/2019/01/08/using-faktory-with-python/) instrction to create client and worker test script and run the script individuly. At bigining all the process work finely, However when I quiet and then stop the work from the Web UI I got this error as below. After that the worker thread will hanging there, therefor I have to kill the worker process manually. My question is that is this the normally way to stop the worker or there is some bug need to fix?  
    ```
    WARNING:faktory.worker:Faktory has quieted this worker, will not run any more tasks
    WARNING:faktory.worker:Faktory has asked this worker to shutdown, will cancel any pending tasks still running 25s time
    INFO:faktory.connection:Disconnected
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\concurrent\futures\process.py", line 101, in _python_exit
        thread_wakeup.wakeup()
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\concurrent\futures\process.py", line 89, in wakeup
        self._writer.send_bytes(b"")
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\multiprocessing\connection.py", line 183, in send_bytes
        self._check_closed()
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\multiprocessing\connection.py", line 136, in _check_closed
        raise OSError("handle is closed")
    OSError: handle is closed
    Exception in thread QueueManagerThread:
    Traceback (most recent call last):
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 917, in _bootstrap_inner
        self.run()
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\concurrent\futures\process.py", line 354, in _queue_management_worker
        ready = wait(readers + worker_sentinels)
    File "C:\Users\1907003\AppData\Local\Programs\Python\Python37\Lib\multiprocessing\connection.py", line 872, in wait
        ov.cancel()
    OSError: [WinError 6] The handle is invalid。
    ```
- environment  
  os : Win10  
  python : python 3.7.3 virtualenv  
  faktory package : 0.4.0
- step to reproduce the error  
1. start the faktory server by docker image  
2. run the worker and client script as following  
    worker  
    ```
    logging.basicConfig(level=logging.INFO)
    time.sleep(1)

    def adder(x, y):
        logging.info("%d + %d = %d", x, y, x + y)

    if __name__ == "__main__":
        w = Worker(queues=['default'], concurrency=1)
        w.register('adder', adder)
    w.run()
    ```  
    client  
    ```
    time.sleep(1)

    with faktory.connection() as client:
    while True:
        client.queue('adder', args=(random.randint(0,1000), random.randint(0,1000)))
        time.sleep(5)
    ```
3. quiet and then stop the worker from Web UI
4. get the error from worker thread

**Comment by mperham** [comment]
This is an issue in faktory_worker_python, not Faktory. Different project and developer.

**Comment by cdrx** [comment]
You may well be the first person to use this on Windows :) 

If the worker is still running 30 seconds after disconnecting it from the web ui, please file this as a bug on the python worker project and I'll look into it. 

https://github.com/cdrx/faktory_worker_python
