### ISSUE TITLE
Faktory Server Crash: concurrent map read and map write

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#274]
This is happening quite a lot, and crashing the whole faktory server

```
I 2020-01-20T16:28:12.046Z Batch: ack success callback for b-gW0gt_qAgCpDpA
I 2020-01-20T16:28:12.046Z Batch b-gW0gt_qAgCpDpA success!
fatal error: concurrent map read and map write

goroutine 75900 [running]:
runtime.throw(0x8949c9, 0x21)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:774 +0x72 fp=0xc00131ba08 sp=0xc00131b9d8 pc=0x42d962
runtime.mapaccess2_faststr(0x7f7960, 0xc0001f0d20, 0xc00178e3c0, 0x10, 0xc0010eece8, 0x7fd1533fc001)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/map_faststr.go:116 +0x48f fp=0xc00131ba78 sp=0xc00131ba08 pc=0x41289f
github.com/mperham/faktory-comm/ent/batch.(*BatchSubsystem).MiddlewarePush(0xc000226050, 0xc000a02a40, 0x929d80, 0xc001745830, 0x701, 0xc000a02a40)
	/Users/mikeperham/src/github.com/mperham/faktory-comm/ent/batch/middleware.go:66 +0x12d fp=0xc00131bad0 sp=0xc00131ba78 pc=0x791c9d
github.com/mperham/faktory-comm/ent/batch.(*BatchSubsystem).MiddlewarePush-fm(0xc000a02a40, 0x929d80, 0xc001745830, 0x1, 0x1c)
	/Users/mikeperham/src/github.com/mperham/faktory-comm/ent/batch/middleware.go:61 +0x48 fp=0xc00131bb10 sp=0xc00131bad0 pc=0x79ec08
github.com/contribsys/faktory/manager.callMiddleware(0xc0001d98c8, 0x1, 0x1, 0x929d80, 0xc001745830, 0xc001745800, 0xc0010eec60, 0x0)
	/Users/mikeperham/src/github.com/contribsys/faktory/manager/middleware.go:64 +0xd3 fp=0xc00131bb50 sp=0xc00131bb10 pc=0x725bc3
github.com/contribsys/faktory/manager.callMiddleware.func1(0x7f8320, 0xc0017457d0)
	/Users/mikeperham/src/github.com/contribsys/faktory/manager/middleware.go:64 +0x57 fp=0xc00131bba0 sp=0xc00131bb50 pc=0x7284c7
github.com/mperham/faktory-comm/pro.pushUniq(0xc000a02a00, 0x929d80, 0xc001745830, 0xc001745830, 0xc001745830)
	/Users/mikeperham/src/github.com/mperham/faktory-comm/pro/unique.go:79 +0x8aa fp=0xc00131bd00 sp=0xc00131bba0 pc=0x782eaa
github.com/contribsys/faktory/manager.callMiddleware(0xc0001d98c0, 0x2, 0x2, 0x929d80, 0xc001745830, 0xc001745800, 0x16, 0x0)
	/Users/mikeperham/src/github.com/contribsys/faktory/manager/middleware.go:64 +0xd3 fp=0xc00131bd40 sp=0xc00131bd00 pc=0x725bc3
github.com/contribsys/faktory/manager.(*manager).Push(0xc0000cb540, 0xc0015d60a0, 0xb0, 0x8280e0)
	/Users/mikeperham/src/github.com/contribsys/faktory/manager/manager.go:208 +0x260 fp=0xc00131be28 sp=0xc00131bd40 pc=0x725390
github.com/contribsys/faktory/server.push(0xc000cb8400, 0xc00019a580, 0xc00090ee40, 0xb2)
	/Users/mikeperham/src/github.com/contribsys/faktory/server/commands.go:70 +0x184 fp=0xc00131be88 sp=0xc00131be28 pc=0x7296a4
github.com/contribsys/faktory/server.(*Server).processLines(0xc00019a580, 0xc000cb8400)
	/Users/mikeperham/src/github.com/contribsys/faktory/server/server.go:301 +0x26f fp=0xc00131bf50 sp=0xc00131be88 pc=0x72dfaf
github.com/contribsys/faktory/server.(*Server).Run.func1(0xc00019a580, 0x92a2c0, 0xc00000e070)
	/Users/mikeperham/src/github.com/contribsys/faktory/server/server.go:143 +0xa5 fp=0xc00131bfc8 sp=0xc00131bf50 pc=0x731415
runtime.goexit()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00131bfd0 sp=0xc00131bfc8 pc=0x45a971
created by github.com/contribsys/faktory/server.(*Server).Run
	/Users/mikeperham/src/github.com/contribsys/faktory/server/server.go:137 +0x18b
```

Full gist: https://gist.github.com/scottrobertson/6ca6b89f1b19e0d1d3777722cad7323a

**Comment by mperham** [comment]
I’m out of the office today but this will be highest priority when I get back.

**Comment by scottrobertson** [comment]
Thanks @mperham 

This is happening multiple times per hour, and is causing a lot of jobs to get stuck in the processing state.

The only "fix" right now i have for that is to stop all workers, login to the redis-cli internally, and drop the `working` key.

**Comment by scottrobertson** [comment]
I have tried disabling statsd logging and throttling to see if it's those, but it still does it with those disabled.

**Comment by mperham** [comment]
It’s happening when pushing a batch job. I’m skiing right now, will be home in a few hours.

**Comment by scottrobertson** [comment]
No problem :) let me know if you need anything from me to help debug when you get a chance.

**Comment by scottrobertson** [comment]
@mperham I am guessing this has been fixed in the pro/ent repo?

What are the chances of getting this out asap? Crashing so often :(

**Comment by mperham** [comment]
Yes, there were two unguarded read accesses; both are now mutex'd. Happy to email you a raw binary but I can't get a release out until tomorrow.

**Comment by scottrobertson** [comment]
If you could email the ent binary, that would be good.
