### ISSUE TITLE
slice bounds out of range on client.Push

### ISSUE THREAD

**Issue by profsmallpine** [contribsys/faktory#286]
Here is the stack trace from the panic:

```
/home/runner/go/pkg/mod/github.com/contribsys/faktory_worker_go@v1.0.0/runner.go:139 +0xea
created by github.com/contribsys/faktory_worker_go.(*Manager).Run
/home/runner/go/pkg/mod/github.com/contribsys/faktory_worker_go@v1.0.0/runner.go:269 +0x348
github.com/contribsys/faktory_worker_go.process(0xc000390d00, 0xf)
/home/runner/go/pkg/mod/github.com/contribsys/faktory_worker_go@v1.0.0/runner.go:31 +0x59
github.com/contribsys/faktory_worker_go.(*Manager).Register.func1(0x1268a60, 0xc000261b00, 0xc0000f4c80, 0x3, 0x1955520)
/home/runner/work/second-child/second-child/pkg/faktory/worker.go:51
github.com/xy-planning-network/second-child/pkg/faktory.(*Worker).sourceSync(...)
/home/runner/work/second-child/second-child/pkg/procedures/source.go:202 +0x67b
github.com/xy-planning-network/second-child/pkg/procedures.(*Source).Sync(0xc000366340, 0x9, 0x0, 0xa)
/home/runner/work/second-child/second-child/pkg/procedures/gmail.go:71 +0xa06
github.com/xy-planning-network/second-child/pkg/procedures.(*Gmail).Sync(0xc000249c90, 0xc000b38ee0, 0xc000b38ee0, 0xc00048e780)
/home/runner/work/second-child/second-child/pkg/faktory/faktory.go:53 +0x126
github.com/xy-planning-network/second-child/pkg/faktory.(*Service).AddGmailSyncFull(0xc0004c81f0, 0x9, 0xc000b38ee0, 0xe4b520)
/home/runner/go/pkg/mod/github.com/contribsys/faktory@v1.2.0-1.0.20200205221243-a3a6398bf32c/client/client.go:328 +0xd2
github.com/contribsys/faktory/client.(*Client).Push(0xc00047c140, 0xc0006b1b80, 0x1024f5b, 0xa)
/home/runner/go/pkg/mod/github.com/contribsys/faktory@v1.2.0-1.0.20200205221243-a3a6398bf32c/client/client.go:456 +0x2b
github.com/contribsys/faktory/client.(*Client).ok(0xc00047c140, 0xc0000a0a20, 0x101d43a, 0x4)
/home/runner/go/pkg/mod/github.com/contribsys/faktory@v1.2.0-1.0.20200205221243-a3a6398bf32c/client/client.go:518 +0x2f
github.com/contribsys/faktory/client.ok(0xc0000a0a20, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/contribsys/faktory@v1.2.0-1.0.20200205221243-a3a6398bf32c/client/client.go:555 +0x72
github.com/contribsys/faktory/client.readResponse(0xc0000a0a20, 0x2, 0x0, 0x0, 0xc000249190, 0x672aba)
/opt/hostedtoolcache/go/1.13.7/x64/src/bufio/bufio.go:437 +0x73
bufio.(*Reader).ReadBytes(0xc0000a0a20, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc000ba8ed4)
/opt/hostedtoolcache/go/1.13.7/x64/src/bufio/bufio.go:334 +0x22d
bufio.(*Reader).ReadSlice(0xc0000a0a20, 0xa, 0xc000248f38, 0x4c98d8, 0x0, 0x0, 0xc000249ef0)
goroutine 41 [running]:
panic: runtime error: slice bounds out of range [7:5]
```

I saw [this issue](https://github.com/contribsys/faktory/issues/130) describing how the client is not thread-safe. I updated my client connection based on xescugc comments.

```
pool, err := worker.NewChannelPool(0, 5, func() (worker.Closeable, error) {
	return client.Open()
})
if err != nil {
	return services, procs, err
}
conn, err := pool.Get()
if err != nil {
	return services, procs, err
}
pc := conn.(*worker.PoolConn)
cli, ok := pc.Closeable.(*client.Client)
if !ok {
	return services, procs, domain.ErrorUnexpected
}
```

I am then sharing `cli` across threads in `s.Client` to call:

```
job := client.NewJob("GmailSyncFull", 2)
job.SetCustom("unique_for", 1800.0) // Job is unique for 30 minutes.
return s.Client.Push(job)
```

Does anything stand out as incorrect about this setup?

**Comment by mperham** [comment]
You cannot share client instances.  You need to create a client Pool; each goroutine will checkout a Client, perform its API calls and then Close() the Client when done so the Client returns to the Pool.

We can definitely improve the documentation here.  Take a look at runner.go Manager, how it creates a Pool and then uses with() to use Clients within that Pool.

**Comment by mperham** [comment]
It's possible the Context interface in types.go needs to expose a Pool for jobs to use.

Oh btw this is a fwg issue, not faktory.

**Comment by mperham** [comment]
Ok, I just checked and the API in client/pool.go seems pretty straightforward.  Your app can use its own Pool like so:

```go
import  faktory "github.com/contribsys/faktory/client"

// how to create pool
pool, err := faktory.NewPool(20)

// how to use pool in your job code
pool.With(func(c *faktory.Client) error  {
  c.Push(...some job data...)
})
```

The Pool is thread-safe and can be shared by many goroutines. Change 20 to however many concurrent connections you will need, max.
