### ISSUE TITLE
Workers not receiving any new jobs

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#297]
Over the past week or so, we have had a large % of our workers not receiving any jobs. The only way we can fix this is by killing the workers and letting them restart (I normally use Stop All in the UI).

There are no errors in the worker logs, or the server logs. Need some help debugging this. I am not able to replicate it either, other than when it randomly happens.

**Comment by mperham** [comment]
I wish I had suggestions. We can start a P&T wiki page like Sidekiq has with tips and tools but since there’s no hard data or reproduction, I’m not sure how to proceed.

**Comment by scottrobertson** [comment]
Just did it again :/ only way to solve it is by killing them all.

**Comment by scottrobertson** [comment]
The "Busy" count in the UI reflects that basically no jobs are running too (it does not seem to stop fully, but only some workers run jobs).

Looking at the worker logs, it seems to start a job, and then just never get "done" log line. The jobs are 100% not getting stuck though, as it's happening across all worker jobs, and some of them literally do 1 tiny thing with nothing else.

**Comment by scottrobertson** [comment]
And again

**Comment by scottrobertson** [comment]
Noticed this:

```
MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by scottrobertson** [comment]
I can write to disk just fine inside the container, and disk space is fine.

**Comment by scottrobertson** [comment]
I restarted it, and it was fine. Then suddenly all jobs got stuck and Processed reset to 0.

**Comment by scottrobertson** [comment]
I have just done `config set stop-writes-on-bgsave-error no` for now on the redis instance. I know this is bad, but it was the only way to get it running again that I could find.

**Comment by scottrobertson** [comment]
Happened again today

**Comment by mperham** [comment]
I think recent versions of fwg respond to TTIN, can you get process backtraces from a stuck worker?

**Comment by scottrobertson** [comment]
We use the ruby library. Will that do the same?

**Comment by mperham** [comment]
Yep, I’ve tried to make it a convention for all of my things, Faktory too.

**Comment by scottrobertson** [comment]
```
1 TID-72g WARN: Thread TID-72g
1 TID-72g WARN: /usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/cli.rb:137:in `backtrace'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/cli.rb:137:in `block in handle_signal'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/cli.rb:134:in `each'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/cli.rb:134:in `handle_signal'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/cli.rb:93:in `run'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/bin/faktory-worker:12:in `<top (required)>'
/usr/local/bundle/bin/faktory-worker:23:in `load'
/usr/local/bundle/bin/faktory-worker:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
1 TID-72g WARN: Thread TID-60cw0
1 TID-72g WARN: /usr/local/bundle/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `pop'
/usr/local/bundle/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `block in <class:RubyThreadLocalVar>'
1 TID-72g WARN: Thread TID-60cys
1 TID-72g WARN: /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:337:in `sleep'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:337:in `block in spawn_thread'
1 TID-72g WARN: Thread TID-60d1k heartbeat
1 TID-72g WARN: /usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/launcher.rb:77:in `sleep'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/launcher.rb:77:in `block in heartbeat'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/launcher.rb:59:in `loop'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/launcher.rb:59:in `heartbeat'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/util.rb:16:in `watchdog'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/util.rb:25:in `block in safe_thread'
1 TID-72g WARN: Thread TID-60d4c
1 TID-72g WARN: /usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/worker.rb:152:in `pop'
/usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/worker.rb:152:in `block in run'
/usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/worker.rb:151:in `loop'
/usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/worker.rb:151:in `run'
/usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/worker.rb:96:in `block (2 levels) in start'
1 TID-72g WARN: Thread TID-4em8c processor
1 TID-72g WARN: /usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:314:in `gets'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:314:in `result'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:345:in `ok'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:89:in `block in create_batch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:299:in `transaction'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/client.rb:87:in `create_batch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/batch.rb:107:in `block in jobs'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory.rb:78:in `block in server'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory.rb:77:in `server'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/batch.rb:105:in `jobs'
/app/app/services/bare_baremetrics/state_creator.rb:44:in `process_account'
/app/app/models/bm/api_key.rb:90:in `import'
/app/app/models/bm/api_key.rb:101:in `reconcile'
/app/app/models/bm/account.rb:144:in `block in reconcile'
/app/app/models/bm/account.rb:144:in `each'
/app/app/models/bm/account.rb:144:in `reconcile'
/app/app/models/bm/account.rb:119:in `process'
/app/app/workers/cron/process_worker.rb:27:in `perform'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:148:in `block (2 levels) in process'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/middleware/chain.rb:128:in `block in invoke'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/middleware/batch.rb:20:in `call'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/middleware/chain.rb:130:in `block in invoke'
/usr/local/bundle/gems/honeybadger-4.7.0/lib/honeybadger/plugins/faktory.rb:10:in `call'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/middleware/chain.rb:130:in `block in invoke'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/middleware/chain.rb:133:in `invoke'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:147:in `block in process'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:137:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/rails.rb:38:in `block in call'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/rails.rb:37:in `call'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:133:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/job_logger.rb:7:in `call'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:128:in `block in dispatch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/logging.rb:43:in `with_context'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/logging.rb:37:in `with_job_hash_context'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:127:in `dispatch'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:146:in `process'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:92:in `process_one'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/processor.rb:74:in `run'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/util.rb:16:in `watchdog'
/usr/local/bundle/gems/faktory_worker_ruby-1.0.0/lib/faktory/util.rb:25:in `block in safe_thread'
```

**Comment by scottrobertson** [comment]
The last entry for a job was:

```
2020-06-12T13:12:11.878828502Z 1 TID-4em8c Cron::ProcessWorker JID-a34e412ef03f30b9bab8f763 INFO: start
```

There is 0 chance this job has taken ~12 hours to run. And even then, the worker has a reserve_for of 1 hour.

**Comment by scottrobertson** [comment]
Not seeing any errors in `/var/lib/faktory/db/redis.log` either

**Comment by mperham** [comment]
Is your worker process single threaded, ie concurrency = 1? Looks like it is stuck waiting for a response from Faktory. I need to verify the network timeouts are set up correctly.

**Comment by scottrobertson** [comment]
They are single threaded yeah.

**Comment by mperham** [comment]
What version of Ruby are you running? FWR appears to set up read/write timeouts as expected. Are you using a TLS connection or just plain TCP? I'm worried that there's some edge case with OpenSSL that isn't respecting timeouts or I'm config'ing them incorrectly.

**Comment by scottrobertson** [comment]
Running ruby 2.7.1.

Standard TCP, no SSL. 

Faktory is running in Kubernetes.

**Comment by mperham** [comment]
Whew, that was a roller coaster. No tests unfortunately but I was able to manually verify the timeout didn't work before and now does work with that code. If you run master, let me know how it goes. I'll have a big release push later this month for Faktory.

**Comment by scottrobertson** [comment]
Awesome @mperham thank you. 

Will update tomorrow and let you know.
