### ISSUE TITLE
EOF keystroke causes panic

### ISSUE THREAD

**Issue by squarism** [contribsys/faktory#31]
I was doing something unrelated and found a bug.  Early software, love the project, no judgey mode here.  😄 🎈 

```
./faktory-cli
Faktory 0.5.0
Copyright © 2017 Contributed Systems LLC
[snip]

> ^D
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4129419]

goroutine 1 [running]:
main.repl(0xc42001a280, 0x18, 0x0, 0x0)
	[snip]/faktory/cmd/repl.go:59 +0x419
main.main()
	[snip]/faktory/cmd/repl.go:42 +0x168
```

`exit` and `ctrl-c` do not panic.  I'll poke around and see if anything is easy to fix but I don't know this codebase yet.

**Comment by mperham** [comment]
I can't reproduce the issue:

```
~/src/github.com/contribsys/faktory (master=)$ make build
go generate github.com/contribsys/faktory/webui
go build -o faktory-cli cmd/repl.go
go build -o faktory cmd/daemon.go
~/src/github.com/contribsys/faktory (master=)$ ./faktory-cli
Faktory 0.5.0
Copyright © 2017 Contributed Systems LLC
Licensed under the GNU Public License 3.0
Using RocksDB 5.7.3 at /Users/mikeperham/.faktory/db
> ^D
~/src/github.com/contribsys/faktory (master=)$ 
```

**Comment by squarism** [comment]
Hmm.  Ah, I see.
`Unable to open storage: IO error: While mkdir if missing: ~/.faktory/db`

Well I have an easy fix.  Store is nil when this happens.  Did I miss a init step?

**Comment by mperham** [comment]
Again, really weird that I can't repro:

```
~/src/github.com/contribsys/faktory (master=)$ rm -rf ~/.faktory/db
~/src/github.com/contribsys/faktory (master=)$ ./faktory-cli 
Faktory 0.5.0
Copyright © 2017 Contributed Systems LLC
Licensed under the GNU Public License 3.0
Using RocksDB 5.7.3 at /Users/mikeperham/.faktory/db
> ^D
```

**Comment by mperham** [comment]
The store should auto-create the DB directory if it doesn't exist.  Maybe you don't have ~/.faktory and it won't create that.

**Comment by squarism** [comment]
Yeah, that's it.  `rm -rf ~/.faktory` causes it.  I guess the PR is defensive enough.
