### ISSUE TITLE
Faktory closing connection 

### ISSUE THREAD

**Issue by mcarrf90-bz** [contribsys/faktory#430]
- Which Faktory package and version?

We are currently using faktory-worker: ^4.2.1

- Please include any relevant worker configuration

We have our redis mounted on a t2.small EC2 instance and our workers on Fargate with 5 tasks.

- Please include any relevant error messages or stacktraces

We are receiving this logs constantly:

```{
  "level": 50,
  "time": 1678978804856,
  "pid": 20,
  "source": "faktory",
  "method": "enqueueJob",
  "message": "Connection closed",
  "stack": "Error: Connection closed\n    at Connection.onClose (/app/node_modules/faktory-worker/lib/connection.js:102:45)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at TCP.<anonymous> (net.js:686:12)"
}


{
  "level": 50,
  "time": 1678978804856,
  "pid": 20,
  "source": "faktory",
  "method": "enqueueJob",
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}

**Comment by mperham** [comment]
I'd open this in the `faktory-worker` JS repo. I can't tell what's wrong.
